version: "3.9"

services:
  api:
    build: ./API
    volumes:
      - ./API/source:/USR/werkstuk/source

    environment:
      - PORT
      - POSTGRES_CONNECTION
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

    ports:
      - "80:${PORT}"

    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - 5432:5432
