# This is a basic workflow to help you get started with Actions

name: CI

on:

  pull_request:
    branches: [ main ]


env:
 PORT : 3000
 POSTGRES_USER : user 
 POSTGRES_PASSWORD : user 
 POSTGRES_DB : werkstuk
 POSTGRES_HOST_AUTH_METHOD : trust
 POSTGRES_CONNECTION : postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB}


jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker containers
        run: docker-compose build

      - name: Start docker containers
        run: docker-compose up -d

      # Runs a set of commands using the runners shell
      - name: Run npm start
        run: |
          cd API
          npm ci
          
      - name: Run tests
        run: |
          cd API
          npm test-ci
